#ORGS := $(wildcard */)
include ./.Makefile.orgs.def
all: $(ORGS)
$(ORGS):
	$(MAKE) -C $@ -f ./.Makefile

update: $(addsuffix /update, $(ORGS))

%/update:
	$(MAKE) -C $* -f ./.Makefile update

clean:
	find . -name ".Makefile*" -exec rm {} \;


.PHONY: all $(ORGS) update clean
